name = "shopee-automate"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

# Cloudflare D1 Database
[[d1_databases]]
binding = "DB"
database_name = "shopee_db"
database_id = "4e954e48-18d2-4ddd-a8af-07299906bc1a"
